### ISSUE TITLE
Dev runs but start/main fails

### ISSUE THREAD

**Issue by kyeotic** [jacob-ebey/remix-deno-jit#3]
I'm trying to get this setup with an app and running into this error

```
TypeError: Cannot read properties of undefined (reading 'v2_errorBoundary')
    at https://esm.sh/v113/@remix-run/server-runtime@1.11.1/deno/server-runtime.mjs:8:2617
    at Array.map (<anonymous>)
    at _ (https://esm.sh/v113/@remix-run/server-runtime@1.11.1/deno/server-runtime.mjs:8:2583)
    at _e (https://esm.sh/v113/@remix-run/server-runtime@1.11.1/deno/server-runtime.mjs:8:3386)
    at createRequestHandler (https://esm.sh/@remix-run/deno@1.11.1/server.ts:25:25)
    at file:///home/kyeotic/dev/snow-tracker/src/runtime.ts:107:33
    at async file:///home/kyeotic/dev/snow-tracker/src/runtime.ts:934:28
 ```
 
 Using `deno task dev` works, so its definitely something wrong with the main/prod setup. This is minified code, so debugging it is difficult.

**Comment by kyeotic** [comment]
The issue is caused by [this line](https://github.com/remix-run/remix/blob/main/packages/remix-server-runtime/server.ts#L276). I fixed it by adding a `future: {}` to `createBuildFromManifest` in runtime.

**Comment by lensbart** [comment]
Thanks @kyeotic for this suggestion. I opened https://github.com/jacob-ebey/remix-deno-jit/pull/4
